# Generated by Django 3.2 on 2021-05-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gastoid', models.IntegerField()),
                ('nombre_gasto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_gasto', models.DateField()),
            ],
        ),
    ]
