# Generated by Django 3.2 on 2021-05-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='gastoid',
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha_gasto',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='nombre_gasto',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
