# Generated by Django 3.2 on 2021-05-05 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210505_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_presupuesto', models.CharField(max_length=200, null=True)),
                ('fecha_presupuesto', models.DateField(null=True, unique_for_month=True)),
            ],
        ),
        migrations.AddField(
            model_name='gasto',
            name='valor_gasto',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='nombre_gasto',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.categoria'),
        ),
    ]
