# Generated by Django 3.2 on 2021-05-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210505_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='valor_presupuesto',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
